#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Repo Dispatcher

on: 
  # push: 
  #   branches:
  #     - master
  #schedule:
  #  - cron: 30 18 * * *
  workflow_dispatch:
    inputs:
      param:
        description: 'parameter'
        required: false
        default: ''

env:
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: cancel running workflows
      uses: styfle/cancel-workflow-action@main
      if: contains(${{ github.event.inputs.param }}, 'cw')
      with:
        workflow_id: 4439867
        access_token: ${{ github.token }}

    - name: Load Settings.ini
      run: |
        source "${GITHUB_WORKSPACE}/devices/common/settings.ini"
        if [ -f "devices/${{matrix.target}}/settings.ini" ]; then
          source "${GITHUB_WORKSPACE}/devices/${{matrix.target}}/settings.ini"
        fi
        echo "REPO_URL=${REPO_URL}" >> $GITHUB_ENV
        echo "REPO_BRANCH=${REPO_BRANCH}" >> $GITHUB_ENV

    - name: Trigger Compile
      run: |
        sudo timedatectl set-timezone "$TZ"
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "x86_64", "client_payload": {"target": "x86_64"}}'
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "rockchip_armv8", "client_payload": {"target": "rockchip_armv8"}}'
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "bcm27xx_bcm2711", "client_payload": {"target": "bcm27xx_bcm2711"}}'
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "bcm27xx_bcm2710", "client_payload": {"target": "bcm27xx_bcm2710"}}'
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "bcm27xx_bcm2709", "client_payload": {"target": "bcm27xx_bcm2709"}}'
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "bcm27xx_bcm2708", "client_payload": {"target": "bcm27xx_bcm2708"}}'
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "armvirt_64", "client_payload": {"target": "armvirt_64"}}'
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "mediatek_mt7622", "client_payload": {"target": "mediatek_mt7622"}}'
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "mediatek_filogic", "client_payload": {"target": "mediatek_filogic"}}'
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "ramips_mt7621", "client_payload": {"target": "ramips_mt7621"}}'
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "ramips_mt7620", "client_payload": {"target": "ramips_mt7620"}}'
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "ramips_mt76x8", "client_payload": {"target": "ramips_mt76x8"}}'
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "ipq807x", "client_payload": {"target": "ipq807x"}}'
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "ipq40xx_generic", "client_payload": {"target": "ipq40xx_generic"}}'
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "bcm4908_generic", "client_payload": {"target": "bcm4908_generic"}}'
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "kirkwood_generic", "client_payload": {"target": "kirkwood_generic"}}'
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "ipq806x_generic", "client_payload": {"target": "ipq806x_generic"}}'
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "meson_meson8b", "client_payload": {"target": "meson_meson8b"}}'
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "ipq60xx_generic", "client_payload": {"target": "ipq60xx_generic"}}'
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "mvebu_cortexa9", "client_payload": {"target": "mvebu_cortexa9"}}'
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "bcm53xx", "client_payload": {"target": "bcm53xx"}}'
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "sunxi_cortexa53", "client_payload": {"target": "sunxi_cortexa53"}}'
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "sunxi_cortexa7", "client_payload": {"target": "sunxi_cortexa7"}}'

